package global.enumerations;

public enum JobEnum {
	None,
	BankTellerRole,
	BankSecurityRole,
	CammaranoHostRole,
	CammaranoCookRole,
	CammaranoCashierRole,
	CammaranoWaiterRole,
	CammaranoSharedWaiterRole,
	JiHostRole,
	JiCookRole,
	JiCashierRole,
	JiWaiterRole,
	JiSharedWaiterRole,
	TuHostRole,
	TuCookRole,
	TuCashierRole,
	TuWaiterRole,
	TuShareDataWaiterRole,
	McNealHostRole,
	McNealCookRole,
	McNealCashierRole,
	McNealWaiterRole,
	McNealSharedDataWaiter,
	RedlandHostRole,
	RedlandCookRole,
	RedlandCashierRole,
	RedlandWaiterRole,
	MarketEmployeeRole,
	MarketManagerRole,
	LandlordRole,
	TruckDriverRole, 
}
